# this file is a holder for signal words - topic conversion
# for now, we hard-code values

hand_selected_topic_labels = {
	# world_leaders
	'obama': 'world_leaders',
	'putin': 'world_leaders',
	'merkel': 'world_leaders',
	'jong': 'world_leaders', # kim jong whats-his-face. ultra-jank, please fix
	'netanyahu': 'world_leaders', 
	'trudeau': 'world_leaders',
	'xi': 'world_leaders', # also jank
	'nieto': 'world_leaders',
	'assad': 'world_leaders', # I guess leading half a country is still leading a country
	'theresa': 'world_leaders', # implying Theresa May of the UK
	'hollande': 'world_leaders',
	'duterte': 'world_leaders',
	'trump': 'world_leaders',
	'erdogan': 'world_leaders', # no idea if this will match with the weird g character
	# countries
	'america': 'countries',
	'uk': 'countries',
	'germany': 'countries',
	'mexico': 'countries',
	'canada': 'countries',
	'korea': 'countries',
	'china': 'countries',
	'spain': 'countries',
	'russia': 'countries',
	'japan': 'countries',
	'iran': 'countries',
	'syria': 'countries',
	'afghanistan': 'countries',
	'venezuela': 'countries',
	'phillipines': 'countries',
	'iraq': 'countries',
	'isis': 'countries', # they worked hard. They deserve this
	# politics
        'president': 'politics',
	'government': 'politics',
	'administration': 'politics',
	'washington': 'politics',
	'republican': 'politics',
	'democrat': 'politics',
	'senate': 'politics',
	'senator': 'politics',
	'representative': 'politics',
	'congress': 'politics',
	'bipartisan': 'politics',
	'partisan': 'politics',
	'secretary': 'politics', # for cabinet positions (like Secretary of Defense)
	'cabinet': 'politics', # for cabinet positions
	'filibuster': 'politics',
	'caucus': 'politics',
	'primaries': 'politics',
	'election': 'politics',
	'vote': 'politics',
	'court': 'politics',
	'pentagon': 'politics',
	# economics
	'tariff': 'economics',
	'job': 'economics',
        'export': 'economics',
	'import': 'economics',
	'trade': 'economics',
	'unemployment': 'economics',
	'production': 'economics',
	'bank': 'economics',
	'tax': 'economics',
	'factory': 'economics',
	'loan': 'economics',
	'debt': 'economics',
	'market': 'economics',
	'investment': 'economics',
	'speculation': 'economics',
	'stock': 'economics',
	'bond': 'economics',
	'money': 'economics',
	'dollar': 'economics',
	'economy': 'economics',
	'nafta': 'economics',
	'tpp': 'economics',
	'shipping': 'economics',
	'gold': 'economics',
	'consumer': 'economics', # implying consumer confidence	
	'welfare': 'economics',
	'wage': 'economics',
	'retirement': 'economics',
	'spending': 'economics',
	'saving': 'economics',
	# foreign relations
	'security': 'foreign',
	'border': 'foreign',
	'war': 'foreign',
	'missile': 'foreign',
	'bomb': 'foreign',
	'invade': 'foreign',
	'attack': 'foreign',
	'un': 'foreign',
	'nato': 'foreign',
	'aid': 'foreign',
	'unicef': 'foreign',
	'cia': 'foreign',
	'army': 'foreign',
	'massacre': 'foreign',
	'genocide': 'foreign',
	'surrender': 'foreign',
	'sovreignty': 'foreign',
	'invaded': 'foreign',
	'battle': 'foreign',
	'drones': 'foreign',
	'negotiation': 'foreign',
	'negotiate': 'foreign',
	'diplomacy': 'foreign',
	'embargo': 'foreign',
	'globalization': 'foreign',
	'talk': 'foreign',
	'communism': 'foreign',
	'communist': 'foreign',
	'democracy': 'foreign',
	'democratic': 'foreign',
	'socialism': 'foreign',
	'socialist': 'foreign',
	'fascism': 'foreign',
	'fascist': 'foreign',
	'hegemony': 'foreign',
	'accords': 'foreign',
	'summit': 'foreign',
	'conference': 'foreign',
	'regime': 'foreign',
	'terrorism': 'foreign',
	'terrorist': 'foreign',
	'terror': 'foreign',
	'nuclear': 'foreign',
	'unilateral': 'foreign',
	'bilateral': 'foreign',
	'trilatal': 'foreign',
	'quadrilateral': 'foreign',
	'rectangle': 'foreign', # it's gonna shape the future
	# social
	'race': 'social',
	'racial': 'social',
	'black': 'social',
	'mexican': 'social',
	'asian': 'social',
	'european': 'social',
	'transgender': 'social',
	'gay': 'social',
	'lgbt': 'social',
	'lgbtq': 'social',
	'sex': 'social',
	'marriage': 'social',
	'husband': 'social',
	'wife': 'social',
	'gender': 'social',
	'abortion': 'social',
	'parenthood': 'social', # implying planned parenthood
	'homosexual': 'social',
	'immigrant': 'social',
	'deport': 'social',
	'immigrate': 'social',
	'visa': 'social',
	'h1b': 'social',
	'religion': 'social',
	'christian': 'social',
	'muslim': 'social',
	'jewish': 'social',
	'rape': 'social',
	'freedom': 'social',
	'equal': 'social',
	'equality': 'social',
	'jail': 'social',
	'prison': 'social',
	'urban': 'social',
	'violence': 'social',
	'university': 'social', # may have many false-positives
	'education': 'social',
	'teacher': 'social',
	'school': 'social',
	'test': 'social',
	'opportunity': 'social',
	'drug': 'social',
	'weed': 'social',
	'rifle': 'social',
	'gun': 'social',
	'shooting': 'social',
	'healthcare': 'social',
	'medicare': 'social',
	'medicaid': 'social',
	'insurance': 'social',
	'obamacare': 'social',
	# environment
	'green': 'environment',
	'energy': 'environment',
	'oil': 'environment',
	'solar': 'environment',
	'fracking': 'environment',
	'wind': 'environment',
	'warming': 'environment',
	'weather': 'environment',
	'water': 'environment',
	'conservation': 'environment',
	'park': 'environment',
	'epa': 'environment',
	'gas': 'environment',
	'pollution': 'environment',
	'pollutant': 'environment',
	'minerals': 'environment',
	'natural': 'environment', # implying natural resources
	'tidal': 'environment',
	'biofuel': 'environment',
	'biodegradable': 'environment',
	'carbon': 'environment', # implying carbon emissions
	'biodiesel': 'environment',
	'compostable': 'environment',
	'waste': 'environment',
	'tesla': 'environment', # because ya know, elon musk and all that
	'organic': 'environment',
	'monsanto': 'environment',
	'seed': 'environment',
	'recycle': 'environment'
}

hand_selected_label_index = {
	'world_leaders': 0,
	'countries': 1,
	'politics': 2,
	'economics': 3,
	'foreign': 4,
	'social': 5,
	'environment': 6
}
