# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "State Of The Media"
description:        "Understanding the impact of news articles on presidential approval ratings. Project for Spring 2017 UW CSE NLP Capstone."

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//rms.sexy"
author:             "Drew Dowling, Kevin Liang, and Aakash Sethi"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "//github.com/asethi77/StateOfTheMedia"
  - name:           "Download"
    href:           "//github.com/asethi77/StateOfTheMedia"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
